import secrets
import os

DEBUG = False
PORT = 5000
HOST = "0.0.0.0"
SQLALCHEMY_ECHO = False
SECRET_KEY = os.environ['SECRET_KEY']
SQLALCHEMY_TRACK_MODIFICATIONS = False
WHOOSH_BASE = "whoosh"
# PostgreSQL
SQLALCHEMY_DATABASE_URI = os.environ['SQLALCHEMY_DATABASE_URI']

